### ISSUE TITLE
CSS布局全面指南（PC端+移动端）

### ISSUE THREAD

**Issue by hamigithub** [learning-note/Questions-and-Answers-Web-front-end-development#7]
前言
-------
> 现在，我们被称为前端工程师。然而，早年给我们的称呼却是页面仔。或许是职责越来越大，整体的前端井喷式的发展，使我们只关注了JS，而疏远了CSS和HTML。

其实，我们可能经常在聊组件化，咋地咋地。但是，回过头来思考一下，如果你看到一张设计稿的时候，连布局都不清不楚，谈何组件化呢。所以，我们需要在分清楚组件之前，先来分清楚布局。废话说了这么多，只是想告诉你，布局这个东西真的很重要。本篇内容概括了布局的基础+基本的PC端布局+移动端适配等内容。

正文
-------
或许对于你来说，喜欢 JS 的背后，是看不懂 CSS 的深层。入门级的 CSS 非常简单，但是，精通它却没有想象的容易。我们本篇聊的是布局。前端开发，从拿到设计稿的那一刻，布局的思考就已经开始了。

> 举个例子，建筑师在设计房屋的时候，需要丈量开发地块的长度，以及每栋房屋相对于其他房屋的位置。

在 CSS 布局中，似乎也是这样开始的。我们也会去区分每个元素的尺寸和定位，力争完美的实现整个设计稿。所以，我们的布局应该从定位和尺寸开始聊起

在 CSS 布局中，似乎也是这样开始的。我们也会去区分每个元素的尺寸和定位，力争完美的实现整个设计稿。所以，我们的布局应该从定位和尺寸开始聊起。

定位
-------
定位的概念就是它允许你定义一个元素相对于其他正常元素的位置，它应该出现在哪里，这里的其他元素可以是父元素，另一个元素甚至是浏览器窗口本身。还有就是浮动了，其实浮动并不完全算是定位，它的特性非常的神奇，以至于它在布局中被人广泛的应用，我们会在后文中专门提及它的。

谈及定位，我们就得从 position 属性说起。你能准确的说出position的属性值吗？相信你可以完美地说出这么六个属性值：static、relative、absolute、fixed、sticky、和 inherit。

+ static（默认）：元素框正常生成。块级元素生成一个矩形框，作为文档流的一部分；行内元素则会创建一个或多个行框，置于其父元素中。
+ relative：元素框相对于之前正常文档流中的位置发生偏移，并且原先的位置仍然被占据。发生偏移的时候，可能会覆盖其他元素。
+ absolute：元素框不再占有文档流位置，并且相对于包含块进行偏移（所谓包含块就是最近一级外层元素 position 属性不为 static 的元素，如果没有存在可参照的包含块，则元素框会相对于根元素进行偏移）
+ fixed：元素不再占有文档流位置，并且相对于视窗进行定位
+ sticky：（这是CSS3新增的属性值）粘性定位，官方的介绍比较简单，或许你不能理解。其实，它就相当于 relative 和 fixed 混合。最初会被当作是 relative，相对于原来的位置进行偏移；一旦超过一定阈值之后，会被当成 fixed 定位，相对于视口进行定位。

简单地，介绍一下 position 的属性值的含义后，再来看一下偏移量 top、right、bottom、left 四个属性。

不清楚，当初在初学 CSS 的时候，会不会与 margin 这个属性混淆？其实，它们之间是很容易去辨识地。因为这四个属性值，其实是，定位时的偏移量。偏移量不会对 static 的元素起到作用。而 margin ，相对应的是盒子模型的外边距，它会对每个元素框起到作用，使得元素框与其它元素之间产生空白。

__下面：我们来看一下一些常用定位的偏移__
+ relative：它的偏移是相对于原先在文档流中的位置，如图：
```css
  .demoRelative {
    width: 200px;
    height: 100px;
    background: aqua;
    position: relative;
    top: 70px;
    left: 200px;
  }
```
![image](https://user-images.githubusercontent.com/23024086/56819884-3e7b9d00-687d-11e9-8a7e-d0f80eda32a0.png)

+ absolute：它的偏移量是相对于最近一级 position 不是 static 的祖先元素的。
+ fixed：它的偏移量是相对于视口的。

这里描述的内容，相对于布局来说是最基础的，同时也是非常重要的。需要注意的是，这里的偏移量其实已经涉及到了接下来要说的尺寸。在做自适应布局设计时，往往希望这些偏移量的单位能够使用百分比，或者相对的单位，例如 rem 等。

尺寸
--------
上面谈及到 尺寸的单位——百分比。那么，下面部分我们就围绕着尺寸单位展开。

尺寸，我们就应该从单位聊起，对于 px 这个单位，做网页的应该再熟悉不过了，因此不多做介绍。

那么，我们可以来介绍一下下面的几个单位：

+ 百分比：百分比的参照物是父元素，50%相当于父元素 width 的50%
+ rem：这个对于复杂的设计图相当有用，它是HTML 的 font-size 的大小
+ em：它虽然也是一个相对的单位，相对于父元素的 font-size，但是，并不常用，主要是计算太麻烦

单位只是一个来定义元素大小的相应参考。另一个概念，或许可以用房子来打一个比方，在早年每栋房子都会在房子的外围建一层栅栏，使得整一块地区可以看成房子+内部地块+栅栏+外围地块的模型。而在 CSS 中，每个元素也会有 __盒子模型__ 的概念。

__盒子模型__ ：每个元素，都会形成一个矩形块，主要包括四部分：margin（外边距）+border（边框）+padding（内边距）+content（内容）

CSS 中存在两种不同的盒子模型，可以通过 box-sizing 设置不同的模型。两种盒子模型，主要是 width 的宽度不同。如图：
![image](https://user-images.githubusercontent.com/23024086/56820542-cdd58000-687e-11e9-86e7-93a97b41afb1.png)

这是标准盒子模型，可以看到 width 的长度等于 content 的宽度；而当将 box-sizing 的属性值设置成 border-box 时，盒子模型的 width=border+padding+content的总和。

可以看出，对于不同的模型的宽度是不同的。宽度默认的属性值是 auto，这个属性值会使得内部元素的长度自动填充满父元素的 width。如图：
> width:auto;

![image](https://user-images.githubusercontent.com/23024086/56846314-6cee8c00-6900-11e9-876c-e07507aac136.png)

但是，auto 这个属性值表示的是浏览器自动计算。这种自动计算，需要一个基准，一般浏览器都是允许高度滚动的，所以，会导致一个问题——浏览器找不到垂直方向上的基准。

同样的道理也会被应用在 margin 属性上。相信如果考擦居中时，水平居中你可能闭着眼睛都能写出来，但是垂直居中却绕着脑袋想。这是因为如果是块级元素水平居中只要将水平方向上的 margin 设置成 auto 就可以了。但是垂直方向上却没有这么简单，因为你设置成 auto 时，margin 为 0 。这个问题，还是需要仔细思考一下的。

到此为止，布局最基本的部分就剩下 __浮动__ 这一块了。

浮动
--------------

浮动，这是一个非常有意思的东西，在布局中被广泛的应用。最初，设计浮动时，其实并不是为了布局的，而是为了实现文字环绕的特效，如图：

![image](https://user-images.githubusercontent.com/23024086/56846565-67df0c00-6903-11e9-8ad4-864a0236dc1e.png)

但是，浮动并不是仅仅这样而已。何为浮动？浮动应该说是‘自成一派’，类似于PS中的图层一样，浮动的元素会在浮动层上面进行排布，而在原先文档流中的元素位置，会被以某种方式进行删除，但是还是会影响布局。你可能会觉得有疑问，什么叫影响布局？下面举个例子：

首先，我们准备两个颜色盒子，如图：
> 浮动前：

![image](https://user-images.githubusercontent.com/23024086/56847171-564d3280-690a-11e9-8d84-286cc84ee2b5.png)

接着，我们将 left 盒子设置成左浮动，如图：
> 浮动后：

![image](https://user-images.githubusercontent.com/23024086/56847269-a37dd400-690b-11e9-81b8-cd85f96b5291.png)

可以发现，虽然 left盒子 因为左浮动，而使得原先元素在普通文档流中占有的位置被删除，但是，当 right盒子 补上原先的位置时，right盒子 中的字体却被挤出来了。这就是所谓的影响布局。

浮动为什么会被使用在布局中呢？因为设置浮动后的元素会形成 BFC (使得内部的元素不会被外部所干扰)，并且元素的宽度也不再自适应父元素宽度，而是适应自身内容。这样就可以，轻松地实现多栏布局的效果。

浮动的内容还需要介绍一块——清除浮动。可以看到，浮动元素，其实对于布局来说，是特别危险的。因为你可能这一块做过浮动，但未做清楚，那么造成高度坍塌的问题。就是上图所示的那种情况。

__清除浮动__  ，最常用的方法有两种：
+ overflow：将父元素的 overflow 属性，设置成 hidden 值。
+ after 伪类：对子元素的 after 伪类进行设置。

这里只是稍微的提上一下。下面我们正式来介绍一下网页的布局，本篇最核心的东西。

最初的布局 —— table
-----------------------------------------

最初的时候，网页简单到可能只有文字和链接。那时候，大家最常用的就是 table。因为 table 可以展示出多个块的排布。

这种布局现在应该不常用了，因为在形色单一的时候，使用起来方便。但是，现在的网页变得越来越复杂，适配的问题也是越来越多，这种布局已经不再合适了。

主要是 div 盒子的出现，可以使得网页进行灵活的排布，使得网页变得繁荣。这时，开发者也开始思索如何去更加清晰地分辨网页的层次。接下来，我们可以看看有哪些比较出名的布局方式。

两栏布局
------------
是否记得，那些一边主体内容，一边目录的网页，如图：
![image](https://user-images.githubusercontent.com/23024086/56848168-505e4e00-6918-11e9-9dea-213d139bb651.png)

类似于上图的布局，可以定义为 __两栏布局__

__两栏布局：__ 一栏定宽，一栏自适应。这样子做的好处是定宽的那一栏可以做广告，自适应的可以作为内容主体。

__实现的方式：__
1.float + margin：
```html
<div class="wrap">
    <div class="left">定宽</div>
    <div class="right">自适应</div>
</div>
```
```css
.left {
    width: 200px;
    height: 940px;
    background: #e61a0c;
    float: left;
    display: table;
    text-align: center;
    line-height: 940px;
    color: #000;
  }

  .right {
    margin-left: 210px;
    height: 940px;
    background: limegreen;
    text-align: center;
    line-height: 940px;
  }
```
![image](https://user-images.githubusercontent.com/23024086/56850099-33ce1000-6930-11e9-966b-6aefa475e820.png)

三栏布局
----------------

三栏布局，也是经常会被使用到的一种布局。

它的特点：两边定宽，然后中间的 width 是auto 的，可以自适应内容，再加上 margin 边距，来进行设定。

三栏布局可以有4种实现方式，每种实现方式都有各自的优缺点。

__1、左右两栏使用 float 属性，中间栏使用 margin 属性进行撑开，注意的是 HTML 的结果__

```html
<div id="threeColumn">
    <div class="left">左栏</div>
    <div class="right">右栏</div>
    <div class="middle">中间栏</div>
  </div>
```
```css
  .left {
    width: 200px;
    height: 300px;
    background: crimson;
    float: left;
  }

  .right {
    width: 200px;
    height: 300px;
    background: forestgreen;
    float: right;
  }

  .middle {
    height: 300px;
    background: darkorange;
    margin: 0 220px;
  }
```

![image](https://user-images.githubusercontent.com/23024086/56850695-7ac00380-6938-11e9-8249-acb144218ccf.png)

> 缺点：1、当宽度小于左右两栏宽度之和时，右侧栏会被挤下去；2、HTML 的结构不正确。

__2、使用 position 定位实现，即左右两栏使用 position 进行定位，中间栏使用 margin 进行定位__

```html
<div id="threeColumn">
    <div class="left">左栏</div>
    <div class="right">右栏</div>
    <div class="middle">中间栏</div>
  </div>
```
```css
  .left {
    width: 200px;
    height: 300px;
    background: crimson;
    position: absolute;
    top: 0;
    left: 0;
  }

  .right {
    width: 200px;
    height: 300px;
    background: forestgreen;
    position: absolute;
    top: 0;
    right: 0;
  }

  .middle {
    height: 300px;
    background: darkorange;
    margin: 0 220px;
  }
```
![image](https://user-images.githubusercontent.com/23024086/56850841-94fae100-693a-11e9-8957-f2f35b85fbbb.png)

> 优点：HTML 结构正常。
> 缺点：当父元素有内外边距时，会导致中间栏的位置出现偏差

__3、使用 float 和 BFC 配合 — 圣杯布局__

当 middle 的宽度设置为100%，然后将其 float 设置为 left，其中的 main盒子 设置 margin 属性，然后左边栏设置 float 为 left，之后设置 margin 为 -100%，右栏也设置为 float：left，之后 margin-left 为自身大小。

```html
  <div id="threeColumn">
    <div class="middle">
      <div class="main">中间栏</div>
    </div>
    <div class="left">左栏</div>
    <div class="right">右栏</div>
  </div>
```
```css
#threeColumn {
    font-size: 48px;
    color: #fff;
    /*overflow: hidden; !*清除浮动*!*/
  }

  .middle {
    width: 100%;
    float: left;
  }

  .main {
    background: darkorange;
    margin: 0 220px;
  }

  .left {
    width: 200px;
    height: 300px;
    background: crimson;
    float: left;
    margin-left: -100%;
  }

  .right {
    width: 200px;
    height: 300px;
    background: forestgreen;
    float: left;
    margin-left: -200px;
  }
```
![image](https://user-images.githubusercontent.com/23024086/56851380-1bb2bc80-6941-11e9-9035-5c774034e054.png)

> 缺点：1、HTML 结构不正确；   2、多了一层标签。

__4、flex 布局__
```html
  <div id="threeColumn">
    <div class="left">左栏</div>
    <div class="middle">中间栏</div>
    <div class="right">右栏</div>
  </div>
```
```css
  #threeColumn {
    display: flex;
    font-size: 48px;
    color: #fff;
  }

  .left {
    width: 200px;
    height: 300px;
    background: crimson;
  }

  .middle {
    width: 100%;
    background: darkorange;
    margin: 0 20px;
  }

  .right {
    width: 200px;
    height: 300px;
    background: forestgreen;
  }
```
![image](https://user-images.githubusercontent.com/23024086/56851515-b3fd7100-6942-11e9-8929-533d43162f8b.png)

> 缺点：除了兼容性，一般没有太大的缺陷

三栏布局使用较为广泛，不过也是比较基础的布局方式。对于 PC 端的网页来说，使用较多，但是移动端，本身宽度的限制，很难做到三栏的方式。因此，移动端盛行的现在，我们应该掌握一些自适应布局技巧和 flex 等方式。

移动端的时代
----------------------

或许，手机占用了人们大部分的时间，对于前端工程师来说，不仅需要会 H5 和大前端的技术，还需要去适配不同的手机屏幕。PC 端称王的时代已经过去，现在要求的网页都是需要能够去适配 PC 和移动端的。

之前，所聊的两栏和三栏布局，一般只能在 PC 中去使用，在移动端，由于屏幕尺寸有限，很难去做到类似的操作，所以，我们需要来了解新的东西。

__1、媒体查询__

如果你需要一张网页能够在 PC 和移动端都能按照不同的设计稿显示出来，那么你需要做的就是去设置媒体查询。

媒体查询的 CSS 标识符是 @media，它的媒体类型可以分为：
+ all， 所有媒体
+ braille 盲文触觉设备
+ embossed 盲文打印机
+ print 手持设备
+ projection 打印预览
+ screen 彩屏设备
+ speech ‘听觉’类似的媒体类型
+ tty 不适用像素的设备
+ tv 电视

代码示例：
```css
@media screen {
  p.test {font-family:verdana,sans-serif;font-size:14px;}
}
@media print {
  p.test {font-family:times,serif;font-size:10px;}
}
@media screen,print {
  p.test {font-weight:bold;}
}
/*移动端样式*/
@media only screen and (min-device-width : 320px) and (max-device-width : 480px) {
  /* Styles */
}
```

媒体查询的主要原理：它像是给整个 CSS 样式设置了断点，通过给定的条件去判断，在不同的条件下，显示不同的样式。例如：手机端的尺寸在 750px，而 PC 端则是大于 750px 的，我们可以将样式写成：

```css
// 当屏幕的宽度大于750px
@media screen and (min-width: 750px){
  .media{
    height: 100px;
    background: red;
  }
}

// 当屏幕宽度小于750px
@media (max-width: 750px){
  .media{
    height: 200px;
    background: green;
  }
}
```

flex 弹性盒子
---------------------

其实移动端会经常使用到 flex 布局，因为在简单的页面适配方面，flex 可以起到很好的拉伸的效果。我们先看几张图体会一下：
![image](https://user-images.githubusercontent.com/23024086/56852069-f5911a80-6948-11e9-8ac7-200b0cc7ba73.png)
![image](https://user-images.githubusercontent.com/23024086/56852073-00e44600-6949-11e9-954b-bfb32b151d94.png)
![image](https://user-images.githubusercontent.com/23024086/56852090-240ef580-6949-11e9-8074-38c375782ed9.png)

可以从图中看出，这个网页不管屏幕分辨率怎么发生变化，它的高度和位置都不变，而且里面的元素排布也没有发生变化，图标信息总是在左边和薪资状况在右边。

这就是很明显的，flex 布局。flex 可以在移动端适配比较简单的，元素比较单一的页面。

具体的 flex 布局内容，请移步到更详细的 flex 说明。

rem适配
-------------

rem 可以说是移动端适配的一个神器。类似于手淘等界面，都是使用的 rem 进行的适配。这种界面有个特点就是 页面元素的复杂度比较高，而使用 flex 进行布局会导致页面被拉伸，但是上下的高度却没有变化等问题。示例图：
![image](https://user-images.githubusercontent.com/23024086/56852167-2c1b6500-694a-11e9-97e9-c3fbf3db96f6.png)
![image](https://user-images.githubusercontent.com/23024086/56852168-2f165580-694a-11e9-9590-a649888ef63c.png)

具体的讲解可以看这篇比较好的文章。rem传送门。

总结
--------------

分析到这里，布局的很多东西都已经非常的清晰了，一般现在使用较多的都是flex布局，这种布局是真的好用！

+ 定位
+ 尺寸
+ 浮动
+ 最初的布局 —— table
+ 两栏布局
+ 三栏布局
+ 移动端的布局

> 完，原文转自 https://www.jianshu.com/p/b01047f2d1a4
