### ISSUE TITLE
flex 弹性盒子说明

### ISSUE THREAD

**Issue by hamigithub** [learning-note/Questions-and-Answers-Web-front-end-development#8]
Flex 基本概念：
---------------------------------
![image](https://user-images.githubusercontent.com/23024086/56865920-0bb0e080-6a06-11e9-8d93-9920c72a46f7.png)

在 flex 容器中默认存在两条轴，水平主轴(main axis) 和垂直的交叉轴(cross axis)，可以通过修改使垂直方向变为主轴，水平方向变为交叉轴。

在容器中的每个单元块被称之为 flex item，每个项目占据的主轴空间为 (main size), 占据的交叉轴的空间为 (cross size)。

这里需要强调，不能先入为主认为宽度就是 main size，高度就是 cross size，这个还要取决于你主轴的方向，如果你垂直方向是主轴，那么项目的高度就是 main size。

Flex 容器：

首先，实现 flex 布局需要先指定一个容器，任何一个容器都可以被指定为 flex 布局，这样容器内部的元素就可以使用 flex 来进行布局。
```css
.container {
    display: flex | inline-flex;       //可以有两种取值
}
```
分别生成一个块状或行内的 flex 容器盒子。简单说来，如果你使用块元素如 div，你就可以使用 flex，而如果你使用行内元素，你可以使用 inline-flex。

需要注意的是：当设置 flex 布局之后，子元素的 float、clear、vertical-align 的属性将会失效。

有下面六种属性可以设置在容器上，它们分别是：
+ flex-direction
+ flex-wrap
+ flex-flow
+ justify-content
+ align-items
+ align-content

__1. flex-direction：决定主轴的方向(即项目的排列方向)__

默认值：row，主轴为水平方向，起点在左端
![image](https://user-images.githubusercontent.com/23024086/56866091-22583700-6a08-11e9-8352-6d9d8b59ed65.png)

row-reverse：主轴为水平方向，起点在右端
![image](https://user-images.githubusercontent.com/23024086/56866126-66e3d280-6a08-11e9-92df-0b895712b443.png)

column：主轴为垂直方向，起点在上沿
![image](https://user-images.githubusercontent.com/23024086/56866157-c346f200-6a08-11e9-80db-f14c03a6225e.png)

column-reverse：主轴为垂直方向，起点在下沿
![image](https://user-images.githubusercontent.com/23024086/56866167-d5c12b80-6a08-11e9-9158-437571c879b9.png)

__2. flex-wrap: 决定容器内项目是否可换行__

默认情况下，项目都排在主轴线上，使用 flex-wrap 可实现项目的换行。
```css
.container {
    flex-wrap: nowrap | wrap | wrap-reverse;
}
```

默认值：nowrap 不换行，即当主轴尺寸固定时，当空间不足时，项目尺寸会随之调整而并不会挤到下一行。
![image](https://user-images.githubusercontent.com/23024086/56866223-626be980-6a09-11e9-9e74-b663330dccd6.png)

wrap：项目主轴总尺寸超出容器时换行，第一行在上方
![image](https://user-images.githubusercontent.com/23024086/56866243-8b8c7a00-6a09-11e9-9cb4-963de8439cc3.png)

wrap-reverse：换行，第一行在下方
![image](https://user-images.githubusercontent.com/23024086/56866251-a3fc9480-6a09-11e9-99b5-7cdd7c71728c.png)

__3. flex-flow: flex-direction 和 flex-wrap 的简写形式__
```css
.container {
    flex-flow: <flex-direction> || <flex-wrap>;
}

默认值为: row nowrap

  .container {
    display: flex;
    flex-flow:row-reverse wrap;
  }
可以同时设置两个属性值
```

__4. justify-content：定义了项目在主轴的对齐方式。__

```css
.container {
    justify-content: flex-start | flex-end | center | space-between | space-around;
}
```

__建立在主轴为水平方向时测试，即 flex-direction: row__

默认值: flex-start 左对齐
![image](https://user-images.githubusercontent.com/23024086/56866340-8845be00-6a0a-11e9-8fbd-8fd849db9ffb.png)

flex-end：右对齐
![image](https://user-images.githubusercontent.com/23024086/56866346-9d225180-6a0a-11e9-9b76-c11d78947195.png)

center：居中
![image](https://user-images.githubusercontent.com/23024086/56866352-b1664e80-6a0a-11e9-8392-7fdbde505c90.png)
